export { NampiProvider } from "components/NampiProvider";
export {
    useAct,
    useActs,
    useAspect,
    useAspectCreate,
    useAspectDelete,
    useAspects,
    useAspectUpdate,
    useAuthor,
    useAuthors,
    useEvent,
    useEventCreate,
    useEventDelete,
    useEvents,
    useEventUpdate,
    useGroup,
    useGroups,
    useHierarchy,
    usePerson,
    usePersons,
    usePlace,
    usePlaces,
    useSource,
    useSources,
    useTypes,
    useUser
} from "hooks/dataHooks";
export { useAuth } from "hooks/useAuth";
export { usePropertyIris } from "hooks/usePropertyIris";
export { namespaces } from "namespaces";
export type {
    Act,
    ActsQuery,
    Aspect,
    AspectMutationPayload,
    AspectsQuery,
    Author,
    AuthorsQuery,
    CollectionNav,
    CollectionQuery,
    Entity,
    Event,
    EventMutationPayload,
    EventsQuery,
    FetchCollectionResult,
    FetchResult,
    Group,
    GroupsQuery,
    Hierarchy,
    HierarchyItem,
    HierarchyQuery,
    Item,
    Literal,
    LiteralDateTime,
    LiteralNumber,
    LiteralString,
    Person,
    PersonsQuery,
    Place,
    PlacesQuery,
    Source,
    SourceLocation,
    SourcesQuery,
    Type,
    TypesQuery,
    User
} from "types";

