export { NampiProvider } from "components/NampiProvider";
export {
  useAct,
  useActs,
  useAspect,
  useAspects,
  useAuthor,
  useAuthors,
  useClasses,
  useEvent,
  useEvents,
  useGroup,
  useGroups,
  usePerson,
  usePersons,
  usePlace,
  usePlaces,
  useSource,
  useSources,
  useUser,
} from "hooks/dataHooks";
export { useAuth } from "hooks/useAuth";
export { usePropertyIris } from "hooks/usePropertyIris";
export { namespaces } from "namespaces";
export type {
  Act,
  ActsQuery,
  Aspect,
  AspectsQuery,
  Author,
  AuthorsQuery,
  Class,
  ClassesQuery,
  CollectionNav,
  Entity,
  Event,
  EventsQuery,
  FetchCollectionResult,
  FetchResult,
  Group,
  GroupsQuery,
  Item,
  Literal,
  LiteralDateTime,
  LiteralNumber,
  LiteralString,
  Person,
  PersonsQuery,
  Place,
  PlacesQuery,
  Source,
  SourceLocation,
  SourcesQuery,
  User,
} from "types";
